"""Pipeline robustness tests for the `illumeta meta` Python pipeline.

Generated by the pipeline-robustness-tester skill. Each test maps to one
(stage, failure-mode) cell of FAILURE_MATRIX.md. Inputs are tiny synthetic
fixtures only — no heavy R / no `illumeta.py analysis` is invoked.

Stages:
  S1 input resolution  (load_meta_manifest, validators)
  S2 branch loading    (_read_branch_records)
  S3 meta combination  (_random_effect_meta_one, _fisher_partial_conjunction)
  S4 candidate concord (_summarize_branch_concordance)
  S5 output write      (_write_tsv)
"""
from __future__ import annotations

import csv
import math
import os
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from illumeta_meta import (  # noqa: E402
    MetaCohort,
    MetaThresholds,
    _analyze_branch,
    _cohort_column_ids,
    _fisher_partial_conjunction,
    _inv_var_weight,
    _random_effect_meta_one,
    _read_branch_records,
    _resolve_branch_table,
    _safe_p_value,
    _summarize_branch_concordance,
    _validate_cohort_count,
    _validate_thresholds,
    _write_tsv,
    load_meta_manifest,
)

BRANCH = "minfi"
DMP = "Minfi_DMPs_full.csv"


def _write_csv(path: Path, header: list[str], rows: list[list[object]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(header)
        writer.writerows(rows)


def _cohort(tmp_path: Path, header: list[str], rows: list[list[object]]) -> MetaCohort:
    d = tmp_path
    _write_csv(d / DMP, header, rows)
    return MetaCohort(cohort_id="GSEx", result_dir=d)


# --------------------------------------------------------------------------- #
# S1 — input resolution
# --------------------------------------------------------------------------- #
def test_s1_B4_manifest_no_header(tmp_path):
    m = tmp_path / "manifest.tsv"
    m.write_text("", encoding="utf-8")
    with pytest.raises(ValueError, match="no header"):
        load_meta_manifest(m, tmp_path)


def test_s1_A5_manifest_missing_result_dir_column(tmp_path):
    m = tmp_path / "manifest.csv"
    _write_csv(m, ["cohort", "label"], [["GSE1", "x"]])
    with pytest.raises(ValueError, match="result_dir"):
        load_meta_manifest(m, tmp_path)


@pytest.mark.parametrize(
    "field,value,msg",
    [
        ("min_cohorts", 1, "min-cohorts"),
        ("meta_fdr", 1.5, "meta-fdr"),
        ("max_i2", 200.0, "max-i2"),
        ("partial_conjunction_r", 0, "partial-conjunction-r"),
        ("min_abs_delta_beta", -0.1, "min-abs-delta-beta"),
        ("top_n", 0, "top-n"),
    ],
)
def test_s1_F1_threshold_out_of_range(field, value, msg):
    th = MetaThresholds(**{field: value})
    with pytest.raises(ValueError, match=msg):
        _validate_thresholds(th)


def test_s1_A3_too_few_cohorts():
    with pytest.raises(ValueError, match="at least 3 cohorts"):
        _validate_cohort_count(MetaThresholds(min_cohorts=3), n_cohorts=2)


def test_s1_F1_pc_r_exceeds_cohorts():
    with pytest.raises(ValueError, match="cannot exceed the number of cohorts"):
        _validate_cohort_count(MetaThresholds(min_cohorts=2, partial_conjunction_r=5), n_cohorts=3)


# --------------------------------------------------------------------------- #
# S2 — branch record loading
# --------------------------------------------------------------------------- #
def test_s2_A5_missing_required_column(tmp_path):
    c = _cohort(tmp_path, ["CpG", "logFC", "SE"], [["cg1", "0.5", "0.1"]])  # no P.Value
    with pytest.raises(ValueError, match="missing required columns"):
        _read_branch_records([c], BRANCH, DMP, allow_missing_branches=False)


def test_s2_A5_missing_se_and_t(tmp_path):
    c = _cohort(tmp_path, ["CpG", "logFC", "P.Value"], [["cg1", "0.5", "0.01"]])
    with pytest.raises(ValueError, match="SE or t"):
        _read_branch_records([c], BRANCH, DMP, allow_missing_branches=False)


def test_s2_A8_duplicate_cpg_rejected(tmp_path):
    c = _cohort(
        tmp_path,
        ["CpG", "logFC", "SE", "P.Value"],
        [["cg1", "0.5", "0.1", "0.01"], ["cg1", "0.4", "0.1", "0.02"]],
    )
    with pytest.raises(ValueError, match="duplicate CpG"):
        _read_branch_records([c], BRANCH, DMP, allow_missing_branches=False)


def test_s2_A2_header_only_file_is_empty_with_warning(tmp_path):
    c = _cohort(tmp_path, ["CpG", "logFC", "SE", "P.Value"], [])
    records, warnings, _ = _read_branch_records([c], BRANCH, DMP, allow_missing_branches=False)
    assert records == {}
    assert any("no CpG records loaded" in w for w in warnings)


def test_s2_A4_nonnumeric_logfc_coerced_to_nan(tmp_path):
    c = _cohort(tmp_path, ["CpG", "logFC", "SE", "P.Value"], [["cg1", "not_a_number", "0.1", "0.01"]])
    records, _, _ = _read_branch_records([c], BRANCH, DMP, allow_missing_branches=False)
    assert "cg1" in records
    # Non-numeric effect must be NaN (cohort silently dropped for this CpG), never a crash.
    assert math.isnan(records["cg1"]["effects"][0])


@pytest.mark.parametrize("bad_p", ["5.0", "-0.1", "inf", "abc"])
def test_s2_A6_out_of_range_pvalue_is_nan(bad_p):
    assert math.isnan(_safe_p_value(bad_p))


def test_s2_A7_non_utf8_bytes_do_not_crash(tmp_path):
    # Write a CSV containing a non-UTF8 byte (0xFF) in an annotation cell.
    p = tmp_path / DMP
    content = b"CpG,Gene,logFC,SE,P.Value\ncg1,G\xffENE,0.5,0.1,0.01\n"
    p.write_bytes(content)
    c = MetaCohort(cohort_id="GSEx", result_dir=tmp_path)
    records, _, _ = _read_branch_records([c], BRANCH, DMP, allow_missing_branches=False)
    assert "cg1" in records
    assert math.isclose(records["cg1"]["effects"][0], 0.5)


# --------------------------------------------------------------------------- #
# S2b — tier3-aware per-cohort input selection (P0-1)
# --------------------------------------------------------------------------- #
def _touch_tier3(tmp_path: Path) -> None:
    (tmp_path / "Minfi_Tier3_Primary_DMPs.csv").write_text("CpG\n", encoding="utf-8")


def test_s2b_tier3_primary_preferred_when_present(tmp_path):
    _touch_tier3(tmp_path)
    c = MetaCohort(cohort_id="GSEx", result_dir=tmp_path, primary_result_mode="tier3_stratified_meta")
    assert _resolve_branch_table(c, BRANCH, DMP, prefer_tier3=True) == "Minfi_Tier3_Primary_DMPs.csv"


def test_s2b_tier3_low_power_preferred_when_present(tmp_path):
    _touch_tier3(tmp_path)
    c = MetaCohort(cohort_id="GSEx", result_dir=tmp_path, primary_result_mode="tier3_low_power")
    assert _resolve_branch_table(c, BRANCH, DMP, prefer_tier3=True) == "Minfi_Tier3_Primary_DMPs.csv"


def test_s2b_tier3_ineligible_keeps_standard(tmp_path):
    _touch_tier3(tmp_path)  # file present but mode is ineligible -> standard is primary
    c = MetaCohort(cohort_id="GSEx", result_dir=tmp_path, primary_result_mode="tier3_ineligible")
    assert _resolve_branch_table(c, BRANCH, DMP, prefer_tier3=True) == DMP


def test_s2b_tier3_missing_file_is_fatal_by_default(tmp_path):
    # tier3 mode but no Tier3 primary table present -> must NOT silently read the
    # naive-pooled table; default behaviour is fatal.
    c = MetaCohort(cohort_id="GSEx", result_dir=tmp_path, primary_result_mode="tier3_low_power")
    with pytest.raises(ValueError, match="tier3 primary table"):
        _resolve_branch_table(c, BRANCH, DMP, prefer_tier3=True)


def test_s2b_tier3_missing_file_fallback_when_allowed(tmp_path):
    c = MetaCohort(cohort_id="GSEx", result_dir=tmp_path, primary_result_mode="tier3_low_power")
    assert _resolve_branch_table(c, BRANCH, DMP, prefer_tier3=True, allow_missing_tier3=True) == DMP


def test_s2b_prefer_tier3_disabled_keeps_standard(tmp_path):
    _touch_tier3(tmp_path)
    c = MetaCohort(cohort_id="GSEx", result_dir=tmp_path, primary_result_mode="tier3_stratified_meta")
    assert _resolve_branch_table(c, BRANCH, DMP, prefer_tier3=False) == DMP


def test_s2b_user_override_not_auto_upgraded(tmp_path):
    _touch_tier3(tmp_path)
    c = MetaCohort(cohort_id="GSEx", result_dir=tmp_path, primary_result_mode="tier3_stratified_meta")
    assert _resolve_branch_table(c, BRANCH, "Custom.csv", prefer_tier3=True) == "Custom.csv"


# --------------------------------------------------------------------------- #
# S3 — meta combination
# --------------------------------------------------------------------------- #
def test_s3_A9_tiny_se_underflow_no_crash():
    """A positive-but-extreme SE underflows se*se to 0.0; the `se>0` guard must
    not let 1/(se*se) raise ZeroDivisionError."""
    res = _random_effect_meta_one([0.5, 0.5, 0.5], [1e-200, 0.1, 0.1], [True, True, True])
    assert res["k"] == 3
    assert isinstance(res["random_effect"], float)  # finite or NaN, never a crash


def test_s3_A9_tiny_se_yields_zero_weight():
    """The guarded inverse-variance weight is 0 for an underflowing SE and
    unchanged (1/se^2) for a normal SE."""
    assert _inv_var_weight(1e-200, True) == 0.0
    assert _inv_var_weight(0.0, True) == 0.0
    assert _inv_var_weight(float("nan"), True) == 0.0
    assert math.isclose(_inv_var_weight(0.1, True), 100.0)
    assert math.isclose(_inv_var_weight(0.1, True, extra=0.03), 1.0 / 0.04)


def test_s3_A9_degenerate_se_excluded_from_effective_count(tmp_path):
    """Semantic guard: a degenerate-SE cohort must NOT count toward the effective
    cohort total (n_valid_cohorts / min-cohorts gate), only crash-avoidance."""
    cohorts = []
    for i, se in enumerate(["1e-200", "0.10", "0.10"]):  # cohort 0 is degenerate
        d = tmp_path / f"c{i}"
        d.mkdir()
        _write_csv(d / DMP, ["CpG", "logFC", "SE", "P.Value"], [["cg1", "0.5", se, "0.01"]])
        cohorts.append(MetaCohort(cohort_id=f"GSE{i}", result_dir=d, n_con=10, n_test=10))
    ids = _cohort_column_ids(cohorts)
    rows, _summary, _w = _analyze_branch(
        cohorts, ids, BRANCH, DMP,
        MetaThresholds(min_cohorts=2, partial_conjunction_r=2),
        allow_missing_branches=False,
    )
    row = next(r for r in rows if r["CpG"] == "cg1")
    assert row["n_valid_cohorts"] == 2  # degenerate cohort excluded, not 3


def test_s3_D1_all_invalid_returns_nan_no_crash():
    res = _random_effect_meta_one([0.5, 0.5], [0.1, 0.1], [False, False])
    assert res["k"] == 0
    assert math.isnan(res["random_effect"]) and math.isnan(res["fixed_effect"])


def test_s3_A3_single_valid_cohort():
    res = _random_effect_meta_one([0.5, 0.5], [0.1, 0.1], [True, False])
    assert res["k"] == 1
    # Heterogeneity is undefined for k=1 → NaN; the point estimate is still finite.
    assert math.isnan(res["I2"]) and math.isnan(res["tau2"])
    assert math.isfinite(res["random_effect"])


def test_s3_A10_all_nan_pvalues_fisher_pc():
    out = _fisher_partial_conjunction([math.nan, math.nan, math.nan], [True, True, True], r=2)
    assert math.isnan(out)


# --------------------------------------------------------------------------- #
# S4 — candidate concordance
# --------------------------------------------------------------------------- #
def test_s4_A2_zero_candidates_no_crash():
    assert _summarize_branch_concordance([]) == []


# --------------------------------------------------------------------------- #
# S5 — output write
# --------------------------------------------------------------------------- #
def test_s5_A2_empty_rows_writes_valid_tsv(tmp_path):
    out = tmp_path / "empty.tsv"
    _write_tsv(out, [], ["CpG", "logFC"], gzip_output=False)
    assert out.exists()
    assert out.read_text(encoding="utf-8").splitlines()[0] == "CpG\tlogFC"


@pytest.mark.skipif(os.geteuid() == 0, reason="root bypasses file permissions")
def test_s5_C2_readonly_outdir_raises_typed_error(tmp_path):
    ro = tmp_path / "ro"
    ro.mkdir()
    ro.chmod(0o555)
    try:
        with pytest.raises(OSError):
            _write_tsv(ro / "x.tsv", [{"CpG": "cg1"}], ["CpG"], gzip_output=False)
    finally:
        ro.chmod(0o755)
