"""Knapp-Hartung adjustment: agreement with metafor, and containment of its effects.

Two things are pinned here. The first is arithmetic: the adjusted standard error and
t-referred P-value must match metafor's rma(test="knha") on frozen cases. CI has no R,
so metafor's outputs are frozen below rather than recomputed; they were generated by
script from metafor's own output, so no value was transcribed by hand.

The second is containment, and it is the reason this file is longer than the first test.
The adjustment is offered as a sensitivity, not as a new default, so it must not touch
the pooled estimate, the existing columns, or what counts as a core candidate. A change
that silently made Knapp-Hartung the default would move every candidate count a user
has already published, while every test that only checked arithmetic kept passing.
"""

from __future__ import annotations

import math
import unittest

from illumeta_meta import (
    _base_fieldnames,
    _random_effect_meta_one,
    _t_two_sided_p,
)

CASES = [
    # k=2, tau2_positive
    ([0.110200387533098, -0.0124721536760569], [0.059825190821747046, 0.04817560618048968],
     0.0611215203600467, 0.60460103342786),
    # k=2, tau2_positive
    ([-0.0484848737041335, 0.0251147291763364], [0.050990304916205334, 0.038677211066503105],
     0.0360272974817348, 0.926388438967897),
    # k=2, tau2_positive
    ([0.0160223849370951, 0.0698764260539895], [0.022730911445454697, 0.03503801803199421],
     0.026105416854615, 0.396509014430377),
    # k=2, tau2_positive
    ([-0.163329162110331, 0.157255517818578], [0.05866055201775877, 0.06274453126297161],
     0.160290474637194, 0.984870329972149),
    # k=2, tau2_zero
    ([0.0215115594117901, -0.0235720564601829], [0.041522420573935404, 0.04121901293641376],
     0.0225412017305357, 0.966265868560677),
    # k=2, tau2_zero
    ([0.00927396645836831, -0.0404523889509072], [0.05626490386808031, 0.03264563060354229],
     0.0215852622224863, 0.4188858819736),
    # k=2, tau2_zero
    ([-0.0321258418564891, 0.00277669041957962], [0.036871122385554116, 0.030370894157539536],
     0.01712812437762, 0.62790812360854),
    # k=2, tau2_zero
    ([-0.0329909209405996, 0.00160827145423825], [0.047403331740959405, 0.02883834569244465],
     0.0153629326636873, 0.702963362415853),
    # k=3, tau2_positive
    ([0.143229210618178, 0.00279255063144745, 0.113247469277477], [0.04002857138659866, 0.03489493878761587, 0.03349208110381612],
     0.0426439004673967, 0.1834739357948),
    # k=3, tau2_positive
    ([0.241709287795538, 0.10094727611076, 0.341241533141464], [0.07926088141326032, 0.04380278378868532, 0.0730160509154796],
     0.0714788612881781, 0.0919779636967744),
    # k=3, tau2_positive
    ([-0.0193030037630861, -0.013430192371402, 0.198041236029317], [0.055336747650110436, 0.0343790464483456, 0.053572661808316414],
     0.070695845198953, 0.535369406382839),
    # k=3, tau2_positive
    ([0.162589039945885, -0.0602190875974578, 0.156788988394892], [0.05207236076253944, 0.050466733261571826, 0.05686654703358653],
     0.0736365250693896, 0.366813840263492),
    # k=3, tau2_zero
    ([0.046884536441655, -0.0261645463267888, 0.00453282247220965], [0.05400205178349347, 0.0666199077062857, 0.026314538108072345],
     0.0140866204663373, 0.614913509914822),
    # k=3, tau2_zero
    ([-0.00566359376060177, -0.0033872867028899, 0.0324048905768364], [0.045980655536850545, 0.0384361597949306, 0.04146009091055214],
     0.0122836777436182, 0.581034776186908),
    # k=3, tau2_zero
    ([-0.0197756612535485, -0.128425452620219, -0.0275444934951624], [0.0655602261534063, 0.08108029770405593, 0.06360236218233176],
     0.0317245254538558, 0.262693398125246),
    # k=3, tau2_zero
    ([-0.0085059193618422, 0.00963230828518125, -0.0131178117407826], [0.05153362570319498, 0.03324708677468665, 0.03816680460182538],
     0.00752937765745615, 0.835517550041512),
    # k=4, tau2_positive
    ([0.212423730173635, -0.171222768366647, 0.0591990634361323, 0.140914692271635], [0.074213583337103, 0.05925706538938393, 0.06032911517153541, 0.06830112418171864],
     0.0835256233085234, 0.544525722492097),
    # k=4, tau2_positive
    ([0.13456294530883, 0.0919379912752918, 0.0495395424078739, 0.202863619887988], [0.10306461617206568, 0.048998269480994366, 0.055462234253802804, 0.05596617766741767],
     0.0345633013845567, 0.0444438322785276),
    # k=4, tau2_positive
    ([-0.0356886152822294, -0.0391184388006436, -0.0990494509213574, 0.0476645362092469], [0.03869114406209785, 0.03472542184858814, 0.04197643143430811, 0.030816486605885127],
     0.0303770999867838, 0.428811247575773),
    # k=4, tau2_positive
    ([-0.042414408107142, -0.0268176421846071, -0.00477777379739397, 0.0429526364455621], [0.03433624948989948, 0.02271960407769775, 0.018645332501236313, 0.02350258127889687],
     0.0177924445343939, 0.81107060566698),
    # k=4, tau2_zero
    ([-0.0379202166219801, -0.00665417198676632, -0.0276998188445026, 0.0236336528334098], [0.04427086968721539, 0.03348145679979836, 0.029758406638021265, 0.03572754919930314],
     0.0128436214320029, 0.437349455628429),
    # k=4, tau2_zero
    ([0.0258664327288063, -0.0346674927215815, 0.0426897468245482, -0.0405276583176854], [0.061339144996254105, 0.053673244328969305, 0.05179214476171023, 0.05729821455129637],
     0.0214001612214713, 0.957731816609975),
    # k=4, tau2_zero
    ([-0.149296576935317, -0.120398637541027, -0.0931066645355791, -0.0577621572820055], [0.04301700230838472, 0.05527843755132522, 0.038816409496430795, 0.03794020426220389],
     0.0201822947042705, 0.015897176852025),
    # k=4, tau2_zero
    ([-0.000224452067087322, -0.00706615711541758, -0.0144231445634733, 0.0278395917714596], [0.044266715320863285, 0.0342726419727119, 0.0191806610003642, 0.02711108747607752],
     0.0100614522278358, 0.900252097584959),
]


# Two-sided t critical values at alpha = 0.05, from published tables. These pin the
# hand-written regularized incomplete beta independently of metafor: if the continued
# fraction were subtly wrong, agreeing with metafor on 24 CpGs and with the textbook
# here would both have to fail in the same direction.
T_CRITICAL_005 = [
    (1, 12.70620473617469),
    (2, 4.302652729911275),
    (3, 3.182446305284263),
    (4, 2.776445105198305),
    (10, 2.228138851986273),
    (100, 1.983971518523537),
]


def _pad(effects: list[float], ses: list[float]) -> tuple[list[float], list[float], list[bool]]:
    """Pad a k-cohort case out to the 4-slot layout _random_effect_meta_one expects."""
    valid = [True] * len(effects) + [False] * (4 - len(effects))
    return (
        effects + [math.nan] * (4 - len(effects)),
        ses + [math.nan] * (4 - len(ses)),
        valid,
    )


class TDistributionTests(unittest.TestCase):
    def test_matches_published_critical_values(self):
        for df, t in T_CRITICAL_005:
            with self.subTest(df=df):
                self.assertAlmostEqual(_t_two_sided_p(t, df), 0.05, places=10)

    def test_degenerate_inputs(self):
        self.assertEqual(_t_two_sided_p(0.0, 3), 1.0)
        self.assertEqual(_t_two_sided_p(float("inf"), 3), 0.0)
        self.assertEqual(_t_two_sided_p(float("-inf"), 3), 0.0)
        self.assertTrue(math.isnan(_t_two_sided_p(float("nan"), 3)))
        self.assertTrue(math.isnan(_t_two_sided_p(1.0, 0)))

    def test_is_heavier_tailed_than_the_normal(self):
        # The whole point of the adjustment: at the same statistic the t reference must
        # give a larger P-value, and the gap must shrink as df grows.
        from illumeta_meta import _normal_two_sided_p

        previous_gap = None
        for df in (1, 2, 4, 30, 200):
            gap = _t_two_sided_p(2.5, df) - _normal_two_sided_p(2.5)
            self.assertGreater(gap, 0.0, df)
            if previous_gap is not None:
                self.assertLess(gap, previous_gap, df)
            previous_gap = gap


class KnappHartungAgreesWithMetaforTests(unittest.TestCase):
    def test_frozen_cases(self):
        for index, (effects, ses, ref_se, ref_p) in enumerate(CASES):
            with self.subTest(case=index, k=len(effects)):
                res = _random_effect_meta_one(*_pad(list(effects), list(ses)))
                self.assertAlmostEqual(
                    res["random_se_hk"], ref_se, delta=abs(ref_se) * 1e-9
                )
                self.assertAlmostEqual(res["random_p_hk"], ref_p, delta=abs(ref_p) * 1e-9)

    def test_every_stratum_is_covered(self):
        # Guards the generator, not the estimator: a regenerated CASES list that
        # silently lost the tau2 == 0 branch would still pass every assertion above.
        ks = {len(effects) for effects, _ses, _se, _p in CASES}
        self.assertEqual(ks, {2, 3, 4})
        zero_tau2 = 0
        for effects, ses, _se, _p in CASES:
            if _random_effect_meta_one(*_pad(list(effects), list(ses)))["tau2"] == 0.0:
                zero_tau2 += 1
        self.assertGreater(zero_tau2, 0)
        self.assertLess(zero_tau2, len(CASES))


class KnappHartungIsContainedTests(unittest.TestCase):
    def test_pooled_estimate_is_untouched(self):
        for effects, ses, _se, _p in CASES:
            padded = _pad(list(effects), list(ses))
            res = _random_effect_meta_one(*padded)
            # Recomputing the DL pooled effect the long way: if the adjustment had been
            # folded into the weights, these would disagree.
            weights = [
                1.0 / (se * se + res["tau2"])
                for se, ok in zip(padded[1], padded[2])
                if ok
            ]
            expected = sum(
                w * e for w, e in zip(weights, [x for x, ok in zip(padded[0], padded[2]) if ok])
            ) / sum(weights)
            self.assertAlmostEqual(res["random_effect"], expected, delta=abs(expected) * 1e-12)

    def test_normal_reference_columns_survive_the_adjustment(self):
        for effects, ses, _se, _p in CASES:
            res = _random_effect_meta_one(*_pad(list(effects), list(ses)))
            self.assertTrue(math.isfinite(res["random_se"]))
            self.assertTrue(math.isfinite(res["random_p"]))

    def test_at_two_cohorts_only_the_reference_distribution_changes(self):
        """With k = 2 the adjusted standard error equals the unadjusted one exactly.

        This is algebra, not coincidence. For k = 2 the DerSimonian-Laird estimate makes
        the re-weighted dispersion sum equal 1, and the Knapp-Hartung variance is that
        sum divided by df = 1 times the random-effects variance. metafor shows the same
        identity. So at k = 2 the entire effect of the adjustment is the switch from the
        normal to t(1) -- which is severe, because t(1) is Cauchy. Pinned because a
        future reader comparing the two columns will otherwise conclude the flag is
        broken.
        """
        two_cohort = [case for case in CASES if len(case[0]) == 2]
        self.assertGreater(len(two_cohort), 0)
        for effects, ses, _se, _p in two_cohort:
            res = _random_effect_meta_one(*_pad(list(effects), list(ses)))
            if res["tau2"] == 0.0:
                continue  # tau2 truncated: the identity is derived for a positive tau2
            self.assertAlmostEqual(
                res["random_se_hk"], res["random_se"], delta=res["random_se"] * 1e-12
            )
            self.assertGreater(res["random_p_hk"], res["random_p"])

    def test_adjusted_p_is_not_uniformly_larger_but_is_usually_so(self):
        # Knapp-Hartung is not a monotone inflation: when the studies agree more closely
        # than their standard errors imply, it can shrink the SE. Asserting "always
        # larger" would encode a false property that a future refactor could "fix".
        larger = sum(
            1
            for effects, ses, _se, _p in CASES
            if (res := _random_effect_meta_one(*_pad(list(effects), list(ses))))["random_p_hk"]
            > res["random_p"]
        )
        self.assertGreater(larger, len(CASES) // 2)

    def test_output_columns_appear_only_when_requested(self):
        default = _base_fieldnames(["a", "b"])
        for column in ("random_se_hk", "random_p_hk", "random_fdr_hk"):
            self.assertNotIn(column, default)

        requested = _base_fieldnames(["a", "b"], report_knapp_hartung=True)
        for column in ("random_se_hk", "random_p_hk", "random_fdr_hk"):
            self.assertIn(column, requested)

        # Added, not reordered. Stated as an exact identity rather than a prefix slice,
        # because the columns land before the per-cohort block and a slice comparison
        # can pass while the tail has silently shifted.
        hk = {"random_se_hk", "random_p_hk", "random_fdr_hk"}
        self.assertEqual([c for c in requested if c not in hk], default)
        self.assertEqual(len(requested), len(default) + 3)


class DegenerateInputTests(unittest.TestCase):
    def test_single_cohort_has_no_adjustment(self):
        res = _random_effect_meta_one([0.1, math.nan], [0.05, math.nan], [True, False])
        self.assertEqual(res["k"], 1)
        self.assertTrue(math.isnan(res["random_se_hk"]))
        self.assertTrue(math.isnan(res["random_p_hk"]))

    def test_no_usable_cohort_returns_nan(self):
        res = _random_effect_meta_one([math.nan] * 2, [math.nan] * 2, [False, False])
        self.assertTrue(math.isnan(res["random_se_hk"]))
        self.assertTrue(math.isnan(res["random_p_hk"]))

    def test_identical_effects_are_refused_rather_than_reported(self):
        """Cohorts reporting the same effect must not become the top hit in the run.

        The Knapp-Hartung variance is estimated from the dispersion of the study effects
        about the pooled value. When that dispersion is zero the variance is zero and the
        t statistic diverges: metafor returns se = 0 and P = 0 exactly, and an unguarded
        implementation returns whatever floating-point residue survived the cancellation
        -- here about 3e-17, which would rank ahead of every real finding. Over hundreds
        of thousands of CpGs run unattended that is a trap, so this case is reported as
        NaN. The normal-reference columns are unaffected and still carry a usable answer.
        """
        res = _random_effect_meta_one([0.2, 0.2, math.nan, math.nan],
                                      [0.05, 0.05, math.nan, math.nan],
                                      [True, True, False, False])
        self.assertEqual(res["k"], 2)
        self.assertTrue(math.isnan(res["random_se_hk"]))
        self.assertTrue(math.isnan(res["random_p_hk"]))
        self.assertTrue(math.isfinite(res["random_se"]))
        self.assertTrue(math.isfinite(res["random_p"]))

    def test_the_guard_does_not_fire_on_merely_close_agreement(self):
        # The guard must catch annihilation, not concordance. Cohorts that agree closely
        # are exactly what the adjustment is supposed to reward with a small SE.
        res = _random_effect_meta_one([0.2, 0.2001, math.nan, math.nan],
                                      [0.05, 0.05, math.nan, math.nan],
                                      [True, True, False, False])
        self.assertTrue(math.isfinite(res["random_se_hk"]))
        self.assertTrue(math.isfinite(res["random_p_hk"]))


if __name__ == "__main__":
    unittest.main()
