"""Pipeline robustness tests for the `illumeta.py` orchestration pipeline.

Generated by the pipeline-robustness-tester skill. Targets only pure-Python
orchestration functions (no network, no R subprocess, no `analysis` run).

Stages:
  O1 id/timeout validation  (is_valid_gse_id, parse_analysis_timeout)
  O2 GEO URL build          (geo_suppl_url)
  O3 group resolution       (profile_values, score_group_candidate)
  O4 IDAT path resolution   (resolve_idat_dir_argument)
  O5 atomic write           (_atomic_write_text)
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from illumeta import (  # noqa: E402
    _atomic_write_text,
    geo_suppl_url,
    is_valid_gse_id,
    parse_analysis_timeout,
    profile_values,
    resolve_idat_dir_argument,
    score_group_candidate,
)


# --------------------------------------------------------------------------- #
# O1 — identifier / timeout validation
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("gse,expected", [
    ("GSE12345", True), ("GSE1", True),
    ("gse12345", False), ("GSE", False), ("GSE12a", False),
    ("GSE12345 ", False), ("", False), ("GSE-12", False),
])
def test_o1_A4_gse_validation(gse, expected):
    assert is_valid_gse_id(gse) is expected


@pytest.mark.parametrize("bad", [None, 123, 1.5, [], {"x": 1}])
def test_o1_A4_gse_non_string_is_false(bad):
    assert is_valid_gse_id(bad) is False


def test_o1_A6_gse_max_digits_boundary():
    assert is_valid_gse_id("GSE12345678", max_digits=8) is True
    assert is_valid_gse_id("GSE123456789", max_digits=8) is False  # 9 digits


@pytest.mark.parametrize("val", ["0", "none", "off", "unlimited", "false", "-5", 0, -1])
def test_o1_timeout_disable_values_return_none(val):
    assert parse_analysis_timeout(val) is None


def test_o1_timeout_finite_values():
    assert parse_analysis_timeout(3600) == 3600
    assert parse_analysis_timeout("3600") == 3600
    assert parse_analysis_timeout(1.5) == 1.5


@pytest.mark.parametrize("bad", ["abc", "inf", "nan", "1e999", ""])
def test_o1_A4_timeout_garbage_raises_valueerror(bad):
    # Caller wraps this in try/except ValueError; it must raise (not return junk).
    with pytest.raises(ValueError):
        parse_analysis_timeout(bad)


# --------------------------------------------------------------------------- #
# O2 — GEO supplementary URL construction (bucket logic)
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("gse,bucket_prefix", [
    ("GSE1", "GSEnnn"),
    ("GSE999", "GSEnnn"),
    ("GSE1000", "GSE1nnn"),
    ("GSE12345", "GSE12nnn"),
    ("GSE100000", "GSE100nnn"),
])
def test_o2_A6_url_bucket_boundaries(gse, bucket_prefix):
    url = geo_suppl_url(gse)
    assert url == f"https://ftp.ncbi.nlm.nih.gov/geo/series/{bucket_prefix}/{gse}/suppl/"


@pytest.mark.parametrize("bad", ["gse123", "GSE", "GSE12a", "GSE123456789"])
def test_o2_A4_invalid_gse_raises(bad):
    with pytest.raises(ValueError, match="Invalid GSE ID"):
        geo_suppl_url(bad)


# --------------------------------------------------------------------------- #
# O3 — group column resolution
# --------------------------------------------------------------------------- #
def test_o3_A2_empty_column_returns_none():
    assert score_group_candidate("disease", []) is None


def test_o3_A3_single_class_returns_none():
    assert score_group_candidate("disease", ["Tumor"] * 8) is None


def test_o3_A1_all_missing_returns_none():
    assert score_group_candidate("disease", ["", None, "   ", ""]) is None


def test_o3_A7_whitespace_padding_merges_groups():
    """HIGH-1 regression: ' Control ' and 'Control' must be counted as one group
    so a balanced 2-class column is still recognised (not rejected/imbalanced)."""
    values = ["Control", " Control ", "Case", " Case "]
    result = score_group_candidate("disease state", values)
    assert isinstance(result, dict)  # recognised as a candidate, not None
    prof = profile_values(values)
    assert prof["unique_count"] == 2  # padding collapsed


def test_o3_A4_mixed_types_no_crash():
    prof = profile_values([1, "2", None, 3.0, "x"])
    assert prof["unique_count"] >= 1
    assert 0.0 <= prof["numeric_frac"] <= 1.0


def test_o3_A2_profile_values_empty_no_crash():
    prof = profile_values([])
    assert prof["unique_count"] == 0
    assert prof["missing_frac"] == 0.0 and prof["numeric_frac"] == 0.0


# --------------------------------------------------------------------------- #
# O4 — IDAT path resolution
# --------------------------------------------------------------------------- #
def test_o4_A2_empty_arg_returns_none():
    resolved, candidates = resolve_idat_dir_argument("", "config.tsv")
    assert resolved is None and candidates == []


def test_o4_C4_absolute_path_passthrough(tmp_path):
    p = str(tmp_path)
    resolved, candidates = resolve_idat_dir_argument(p, "config.tsv")
    assert resolved == p and candidates == [p]


def test_o4_C1_relative_nonexistent_returns_candidate_no_crash(tmp_path):
    cfg = tmp_path / "configure.tsv"
    cfg.write_text("x\n", encoding="utf-8")
    resolved, candidates = resolve_idat_dir_argument("does_not_exist/idat", str(cfg))
    assert resolved == candidates[0]  # graceful: first candidate, never a crash
    assert resolved.endswith("does_not_exist/idat")


def test_o4_relative_existing_resolves(tmp_path):
    cfg = tmp_path / "configure.tsv"
    cfg.write_text("x\n", encoding="utf-8")
    (tmp_path / "idat").mkdir()
    resolved, _ = resolve_idat_dir_argument("idat", str(cfg))
    assert Path(resolved) == (tmp_path / "idat").resolve()


# --------------------------------------------------------------------------- #
# O5 — atomic text write
# --------------------------------------------------------------------------- #
def test_o5_atomic_write_text_roundtrip(tmp_path):
    dest = tmp_path / "out" / "note.txt"
    dest.parent.mkdir()
    _atomic_write_text("hello\n", str(dest))
    assert dest.read_text(encoding="utf-8") == "hello\n"
    # No stray temp files left behind in the directory.
    assert [p.name for p in dest.parent.iterdir()] == ["note.txt"]


@pytest.mark.skipif(os.geteuid() == 0, reason="root bypasses file permissions")
def test_o5_C2_atomic_write_readonly_raises_oserror(tmp_path):
    ro = tmp_path / "ro"
    ro.mkdir()
    ro.chmod(0o555)
    try:
        with pytest.raises(OSError):
            _atomic_write_text("x", str(ro / "x.txt"))
    finally:
        ro.chmod(0o755)
